# From user `Lazaro` on Slack:
set_theme!(
    rowgap = 5,
    colgap = 5,
    fontsize = 20,
    backgroundcolor = :black, # "#212946",
    cycle = :color,
    palette = (color = COLORS,),
    Axis = (
        xgridcolor = :white,
        ygridcolor = :white,
        backgroundcolor = :black, # "#212946",
        xgridwidth=0.35,
        ygridwidth=0.35,
        xtickalign=0,
        ytickalign=0,
        xtickcolor = :white,
        ytickcolor = :white,
        bottomspinecolor = :white,
        topspinecolor =:white,
        leftspinecolor =:white,
        rightspinecolor =:white,
        xlabelcolor = :white,
        ylabelcolor = :white,
        xlabelsize = 24,
        ylabelsize = 24,
        xticklabelcolor = :white,
        yticklabelcolor = :white,
        xgridvisible = true,
        ygridvisible = true,
    ),
)
